version: '3.8'
services:
  create-catering:
    build: 
      context: ./create-catering

    image: create-catering-service

    container_name: create-catering-service

    env_file:
      - ./create-catering/.env
      
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "8071:8071"
    networks:
      - catering-network

  read-catering:
    build: 
      context: ./read-catering

    image: read-catering-service

    container_name: read-catering-service

    env_file:
      - ./read-catering/.env
      
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "8072:8072"
    networks:
      - catering-network

  update-catering:
    build: 
      context: ./update-catering

    image: update-catering-service

    container_name: update-catering-service

    env_file:
      - ./update-catering/.env
      
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "8073:8073"
    networks:
      - catering-network


  delete-catering:
    build: 
      context: ./delete-catering

    image: delete-catering-service

    container_name: delete-catering-service

    env_file:
      - ./delete-catering/.env
      
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "8074:8074"
    networks:
      - catering-network

networks:
  catering-network:
