openapi: 3.0.0
info:
  title: Microservice Locations Create API
  version: 1.0.0
  description: API for creating locations using GraphQL
servers:
  - url: http://localhost:4003
paths:
  /graphql:
    post:
      summary: Create a new location
      description: Creates a new location associated with a province using a GraphQL mutation.
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token for authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: GraphQL mutation query
                  example: |
                    mutation {
                      createLocation(input: {
                        location_name: "Test location"
                        province_id: 1
                      }) {
                        location_id
                        location_name
                        province_id
                      }
                    }
      responses:
        '200':
          description: Location successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      createLocation:
                        $ref: '#/components/schemas/Location'
        '400':
          description: Bad request, check the provided data
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Invalid input data"
        '401':
          description: Unauthorized, authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Authentication required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Database error occurred"
components:
  schemas:
    Location:
      type: object
      properties:
        location_id:
          type: integer
          description: Generated location ID
          example: 123
        location_name:
          type: string
          description: Name of the location
          example: "Test location"
        province_id:
          type: integer
          description: Province ID
          example: 1
